エディタでのsave,load
coordinote/coordinote pull request #16
Opened 2017-06-23 08:31 UTC by Syaz0326

* エディタ画面でのtile,clipの保存
  * 各ボタンの押下時にsave,loadする
  * tag，col，styは固定

2017-06-23 16:24 UTC, equanz requested changes
ファーストレビューの結果，数点変更が必要と思われます。
単なるコメントも混ざっていると思われるので注視してください。

2017-06-23 16:24 UTC, equanz commented on tsconfig.json
> +    "target": "es5",
詳しくは知りませんが， `es5` と 9行目の `es2015` は設定として矛盾してはいませんか

2017-06-23 16:24 UTC, equanz commented on package.json
> +  "private": true
publish防止という点では良いですね

2017-06-23 16:24 UTC, equanz commented on package.json
> +    "@types/nedb": "^1.8.3",
これの詳細を伺いたいです

2017-06-23 16:24 UTC, equanz commented on edit_screen/write/app/app.component.ts
> +    if(clip_id !== null){
`nullでないとき` という処理に対して，nullの場合の定義がされていません
エラー処理を記述する場合，この部分でエラー処理を記述しても良いのですが `nedb_module` のメソッドに通した際にバリデーションエラーを起こすと思われるのでそのまま通過させたほうが良いと思われます
ただ，用例から察するに `clip_id === null` である場合は`save_clip` を実行する等の対策も有効と考えられます

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/write/app/app.component.ts
> +    console.log(TILE);
全体的にですが `log`  による出力が多いように見受けられます
実装終了時でかまわないので削除等の処理をお願いします

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/edit.js
> +//# sourceMappingURL=edit.js.map
ファイル終端は改行すべき

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/write/app/app.module.js
> +//# sourceMappingURL=app.module.js.map
ファイル終端は改行すべき

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/write/app/app.component.js.map
> +{"version":3,"file":"app.component.js","sourceRoot":"","sources":["app.component.ts"],"names":[],"mappings":";;;;;;;;AAAA,sCAA2C;AAE3C;IAAA;IAOA,CAAC;IAAD,WAAC;AAAD,CAAC,AAPD,IAOC;AAPY,oBAAI;AASjB,IA
ファイル終端は改行すべき

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/write/app/app.component.js
> +//# sourceMappingURL=app.component.js.map
ファイル終端は改行すべき

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/edit.js.map
> +{"version":3,"file":"edit.js","sourceRoot":"","sources":["edit.ts"],"names":[],"mappings":";;AAAA,8EAA2E;AAE3E,2DAAsD;AAEtD,iDAAsB,EAAE,CAAC,eAAe,CAAC,yBAAS,CAAC,CAAC"}
ファイル終端は改行すべき

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/write/app/app.module.js.map
> +{"version":3,"file":"app.module.js","sourceRoot":"","sources":["app.module.ts"],"names":[],"mappings":";;;;;;;;AAAA,sCAAyC;AACzC,8DAA2D;AAC3D,wCAA6C;AAE7C,uDAAoD;AAUpD,IAAa,SAAS;IAAtB;IAAyB,CAAC;IAAD
ファイル終端は改行すべき

2017-06-23 16:24 UTC, rikyuusima commented on edit_screen/write/app/app.component.ts
> +  idx: number;
本来 `integer` が望ましいですが，デフォルトでは定義不能なようなので気をつけて使用してください
ただ，`nedb_module` でバリデーションエラーを起こすと思われるので大きな問題ではないです

2017-06-23 23:21 UTC, Syaz0326 commented on tsconfig.json
> +    "target": "es5",
パクってきたやつなので修正しておきます

2017-06-23 23:25 UTC, Syaz0326 commented on package.json
> +    "@types/nedb": "^1.8.3",
nedb_moduleが読み込めなかった時に入れたやつを消し忘れていただけなので消してpushします
(TypeScript用の型定義ファイルです)

2017-06-23 23:26 UTC, Syaz0326 commented on edit_screen/write/app/app.component.ts
> +    console.log(TILE);
各機能の実装が終わり次第削除します

2017-06-23 23:53 UTC, Syaz0326 commented on edit_screen/write/app/app.component.ts
> +  idx: number;
了解です

2017-06-23 23:55 UTC, Syaz0326 commented on edit_screen/write/app/app.component.ts
> +    if(clip_id !== null){
修正してpushします

2017-06-24 00:14 UTC, Syaz0326 commented on edit_screen/edit.js
> +//# sourceMappingURL=edit.js.map
こいつらはTypeScriptをコンパイルして出てきたものなので…
tscの設定で出来ないか探してみます

2017-06-24 07:19 UTC, equanz approved these changes

2017-06-24 07:19 UTC, rikyuusima commented
LGTM

2017-06-24 07:21 UTC, rikyuusima commented
思うに，これってedit_screenからscreenに飛ばすべき案件では?
edit_writeからedit_screenはPR必要なかったような

2017-06-24 07:21 UTC, merged