electronとserverの同時起動
coordinote/coordinote pull request #25
Opened 2017-07-07 10:30 UTC by amataku

* serverを改善
* serverとelectronの同時起動を実装

2017-07-07 13:55 UTC, Syaz0326 approved these changes
よさ

2017-07-07 14:05 UTC, equanz reviewed
無名関数 `function(hoge, fuga){}` はこのような使用方法では `(hoge, fuga) => {}`とすることが出来ます (arrow関数)
ぜひ実施してください

2017-07-07 16:38 UTC, equanz requested changes
`nedb` に関しては必ず実装後単体テストを実施してみてください
頑張ってください 👍

2017-07-07 16:38 UTC, equanz commented on server/app.js
> +http.listen(3000,() => {
ポート番号をマジックナンバーにするのはよろしくない
定数変数が良いかと思います

2017-07-07 16:38 UTC, rikyuusima commented on server/html/svg-canvas.html
>          <script src="/socket.io/socket.io.js"></script>
動作可能か確認の必要あり

2017-07-07 16:38 UTC, rikyuusima commented on server/app.js
>      nedb.set_tile(TILE,(save_doc) => {
`nedb` の requireがされていないので動きません

2017-07-07 16:38 UTC, rikyuusima commented on server/app.js
>      nedb.set_clip(tag,(newclip) => {
`nedb` の requireがされていないので動きません

2017-07-07 16:38 UTC, rikyuusima commented on server/app.js
> +    nedb.get_clips_tags((alltags) => {
`nedb` の requireがされていないので動きません

2017-07-07 16:38 UTC, rikyuusima commented on server/app.js
> +  socket.on('pathdata_pathFloat_from_canvas',(Floatdata) => {
`pathFloat` という命名規則より， `Floatdata` の方が 33行目の規則と合致しているように思います

2017-07-07 16:38 UTC, rikyuusima commented on server/app.js
>      socket.broadcast.emit('pathdata_PathFloat_from_server',Floatdata)
28行目と違って `PathFloat` の1文字目が大文字な点は統一させたほうが良いと思います

2017-07-07 16:38 UTC, rikyuusima commented on server/app.js
> +    nedb.get_clips_tags((alltags) => {
`nedb` の requireがされていないので動きません

2017-07-07 16:38 UTC, rikyuusima commented on server/html/svg-canvas.html
>          <script src="https://satoshikawabata.github.io/SVGCatmullRomSpline/bundle.js"></script>
できるようならばローカル環境に `.js` を保持するようにしたいです

2017-07-07 16:38 UTC, rikyuusima commented on server/html/svg-canvas.html
>          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
`jQuery` は `npm` からロードする方がいいと思います

2017-07-07 16:38 UTC, rikyuusima commented on server/js/draw.js
>  var history_array = []
`var` を `let` 等で表現することは出来ませんでしたか?

2017-07-08 12:53 UTC, maturu commented on main.js
> +require('./server/app.js')
絶対パスでなくても良いでしょうか？

2017-07-10 00:47 UTC, amataku commented on main.js
> +require('./server/app.js')
ディレクトリ構成を整えておけば問題ないと思いますが修正を検討しておきます

2017-07-10 12:29 UTC, maturu commented on server/js/resize.js
>  $(window).resize(() => {
画面のサイズはcssで実装するべきでした。ごめんなさい。私が直した方が良いですか？

2017-07-10 12:31 UTC, amataku commented on server/js/resize.js
>  $(window).resize(() => {
どこをどう直せばいいか教えてくれたらこちらで直します

2017-07-10 12:39 UTC, maturu commented on server/js/resize.js
>  $(window).resize(() => {
これは、bodyのheightを動的に変化させるコードなのでHTML のheadタグの中にviewportを設定した後、height: 100vh; をbody の cssに対応させれば出来るかもです。

2017-07-10 12:39 UTC, maturu commented on server/js/resize.js
>  $(window).resize(() => {
これは、bodyのheightを動的に変化させるコードなのでHTML のheadタグの中にviewportを設定した後、height: 100vh; をbody の cssに対応させれば出来るかもです。

2017-07-11 17:19 UTC, amataku commented
修正が終了したので確認をお願いいたします

2017-07-11 17:24 UTC, equanz approved these changes
Socket名に関して今後フロントとの設計が必要かと思います。
現段階では問題点を解決していただけていると思います。
お疲れ様でした。

2017-07-11 19:32 UTC, maturu approved these changes
お疲れ様です。

2017-07-11 19:33 UTC, merged