Screen
coordinote/coordinote pull request #60
Opened 2017-07-25 13:13 UTC by maturu

- coordinote version 1.0.0

2017-07-25 13:27 UTC, equanz requested changes
今後のバグの種になりそうな点を見つけたので修正をお願いします。
余談ですが，8000行弱のレビューも大変です…。

2017-07-25 13:27 UTC, rikyuusima commented on gulpfile.js
>  gulp.task('webserver', () => {
@Syaz0326 angular2 serverタスク(l19-l29)は不要であればそのように言ってあげてください(おそらくscreenから直接編集してくれると思うので)

2017-07-25 13:27 UTC, rikyuusima commented on export_screen/js/footer.js
> +$('.move').click(() => {
これはクラスよりidで実装するほうが無難では?

2017-07-25 13:39 UTC, maturu commented on export_screen/js/footer.js
> +$('.move').click(() => {
修正しました。

2017-07-25 14:31 UTC, amataku requested changes
行数多すぎて見逃しがあるかもしれません。
すみません。
ファイルの終端に改行がないものがあるのですが自動生成の物でしょうか？

2017-07-25 14:31 UTC, amataku commented on edit_screen/less/screen_view.less
> +            outline: none
;はいらないのでしょうか？

2017-07-25 14:31 UTC, amataku commented on export_screen/css/export_style.css
> +	display:block;
インデントが大きい気がします

2017-07-25 17:24 UTC, maturu commented on export_screen/css/export_style.css
> +	display:block;
修正しました

2017-07-26 05:21 UTC, Syaz0326 approved these changes
自分からは特に無いです

2017-07-26 05:21 UTC, Syaz0326 commented on edit_screen/edit.ts
> +platformBrowserDynamic().bootstrapModule(AppModule);
セミコロンがついたままなのでgulpの修正と一緒にpushしました

2017-07-26 05:21 UTC, Syaz0326 commented on gulpfile.js
>  gulp.task('webserver', () => {
修正してpushしました

2017-07-26 09:12 UTC, equanz approved these changes

2017-07-26 12:51 UTC, rikyuusima commented on edit_screen/less/screen_view.less
> +            outline: none
面倒なので私で追記しました

2017-07-26 13:28 UTC, amataku approved these changes

2017-07-26 13:28 UTC, merged