Edit screen
coordinote/coordinote pull request #66
Opened 2017-08-08 14:48 UTC by Syaz0326

* delete_clip時にcreate clip と load_clipだけの画面に遷移するように変更
* defind -> defined
* sidebarからの要素はみ出しの修正
* common css の適用
* menu-barをAngularに移植

2017-08-08 15:28 UTC, maturu requested changes

2017-08-08 15:28 UTC, maturu commented on edit_screen/css/screen_view.css
>    top: 15vh;
`box-shadow: 1px 1px 1px rgba(136, 134, 238, 0.4);`を追加してください。

2017-08-08 15:32 UTC, maturu commented on edit_screen/css/screen_view.css
>    top: 15vh;
間違えました。`box-shadow: 0 0 4px rgba(136, 134, 238, 0.4);`に変更してください。

2017-08-08 15:34 UTC, maturu approved these changes
LGTM

2017-08-08 15:38 UTC, amataku approved these changes

2017-08-09 11:32 UTC, equanz requested changes
export側と定義付けされた点が素晴らしい
!importantに関して再検討をお願いします

2017-08-09 11:32 UTC, rikyuusima commented on edit_screen/less/screen_view.less
> +      width: 100% !important;
どうしても `!important` を使わなければなりませんか…
再検討してもらえるとありがたいです

2017-08-09 11:32 UTC, rikyuusima commented on edit_screen/less/screen_view.less
> +        width: 100% !important;
どうしても `!important` を使わなければなりませんか…
再検討してもらえるとありがたいです

2017-08-09 11:32 UTC, rikyuusima commented on edit_screen/less/screen_view.less
> +              width: 100% !important;
どうしても `!important` を使わなければなりませんか…
再検討してもらえるとありがたいです

2017-08-11 04:40 UTC, tadakazu-yashiro-mulodo commented on edit_screen/less/screen_view.less
> +        width: 100% !important;
ここだけはもとからあるスタイルを上書きしなければならないので許してください

2017-08-11 04:42 UTC, Syaz0326 commented on edit_screen/less/screen_view.less
> +        width: 100% !important;
ここはスタイルの上書きが必要なので許してください

2017-08-11 14:27 UTC, equanz approved these changes

2017-08-11 14:27 UTC, merged